services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    # You can specify a specific version like mongo:7.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
